<?php

namespace monitoring\ApplicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * checkUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pingUrlRepository extends EntityRepository
{
}
