application_homepage:
    pattern:  /
    defaults: { _controller: ApplicationBundle:Default:index }
    requirements:
        _method:  GET

application_live:
    pattern:  /live
    defaults: { _controller: ApplicationBundle:Default:live }
    requirements:
        _method:  GET

moniteasy_check_create:
    pattern:  /create_check
    defaults: { _controller: ApplicationBundle:check:createCheck }
    requirements:
        _method:  GET|POST
