################################################################
# front
front_home:
    pattern:  /
    defaults: { _controller: ApplicationBundle:Front:home }
    requirements:
        _method:  GET

front_about:
    pattern:  /about
    defaults: { _controller: ApplicationBundle:Front:about }
    requirements:
        _method:  GET

front_download:
    pattern:  /download
    defaults: { _controller: ApplicationBundle:Front:download }
    requirements:
        _method:  GET

front_apidoc:
    pattern:  /apidoc
    defaults: { _controller: ApplicationBundle:Front:apidoc }
    requirements:
        _method:  GET

front_contact:
    pattern:  /contact
    defaults: { _controller: ApplicationBundle:Front:contact }
    requirements:
        _method:  GET

front_signIn:
    pattern:  /signIn
    defaults: { _controller: ApplicationBundle:Front:signIn }
    requirements:
        _method:  GET

front_signUp:
    pattern:  /signUp
    defaults: { _controller: ApplicationBundle:Front:signUp }
    requirements:
        _method:  GET

################################################################
#back

backend_live:
    pattern:  /home
    defaults: { _controller: ApplicationBundle:Default:home }
    requirements:
        _method:  GET

backend_dashboard:
    pattern: /dashboard
    defaults: { _controller: ApplicationBundle:Default:dashBoard }
    requirements:
        _method:  GET

backend_notification:
    pattern: /notification
    defaults: { _controller: ApplicationBundle:Default:alert }
    requirements:
        _method:  GET

backend_account:
    pattern: /account
    defaults: { _controller: ApplicationBundle:Default:account }
    requirements:
        _method:  GET


backend_post:
    pattern:  /post
    defaults: { _controller: ApplicationBundle:Check:postCheck }
    requirements:
        _method:  POST

################################################################
#crud checkUrl

backend_check_create:
    pattern:  /create_check
    defaults: { _controller: ApplicationBundle:Check:putCheck }
    requirements:
        _method:  GET|POST

backend_check_read:
    pattern:  /read_check
    defaults: { _controller: ApplicationBundle:Check:getCheck }
    requirements:
        _method:  GET

backend_check_readAll:
    pattern:  /readAll_check
    defaults: { _controller: ApplicationBundle:Check:getAllCheck }
    requirements:
        _method:  GET

backend_check_update:
    pattern:  /update_check
    defaults: { _controller: ApplicationBundle:Check:postCheck }
    requirements:
        _method:  GET|POST

backend_check_delete:
    pattern:  /delete_check
    defaults: { _controller: ApplicationBundle:Check:deleteCheck }
    requirements:
        _method:  GET|DELETE