################################################################
# front
front_home:
    pattern:  /
    defaults: { _controller: ApplicationBundle:Front:home }
    requirements:
        _method:  GET

front_about:
    pattern:  /about
    defaults: { _controller: ApplicationBundle:Front:about }
    requirements:
        _method:  GET

front_download:
    pattern:  /download
    defaults: { _controller: ApplicationBundle:Front:download }
    requirements:
        _method:  GET

front_apidoc:
    pattern:  /apidoc
    defaults: { _controller: ApplicationBundle:Front:apidoc }
    requirements:
        _method:  GET

front_contact:
    pattern:  /contact
    defaults: { _controller: ApplicationBundle:Front:contact }
    requirements:
        _method:  GET|POST

front_signIn:
    pattern:  /signIn
    defaults: { _controller: ApplicationBundle:Front:signIn }
    requirements:
        _method:  GET

front_signUp:
    pattern:  /signUp
    defaults: { _controller: ApplicationBundle:Front:signUp }
    requirements:
        _method:  GET

################################################################
#back

backend_live:
    pattern:  /backend/home
    defaults: { _controller: ApplicationBundle:Default:home }
    requirements:
        _method:  GET

backend_dashboard:
    pattern: /backend/dashboard
    defaults: { _controller: ApplicationBundle:Default:dashBoard }
    requirements:
        _method:  GET

backend_notification:
    pattern: /backend/notification
    defaults: { _controller: ApplicationBundle:Default:notification }
    requirements:
        _method:  GET

backend_account:
    pattern: /backend/account
    defaults: { _controller: ApplicationBundle:Default:account }
    requirements:
        _method:  GET

################################################################
#crud checkUrl

backend_check_create:
    pattern:  /backend/check/create
    defaults: { _controller: ApplicationBundle:Check:putCheck }
    requirements:
        _method:  GET|POST

backend_check_readAll:
    pattern:  /backend/check/read
    defaults: { _controller: ApplicationBundle:Check:getAllCheck }
    requirements:
        _method:  GET

backend_check_read:
    pattern:  /backend/check/read/{idCheckUrl}
    defaults: { _controller: ApplicationBundle:Check:getCheck }
    requirements:
        _method:  GET

backend_check_update:
    pattern:  /backend/check/update/{idCheckUrl}
    defaults: { _controller: ApplicationBundle:Check:postCheck }
    requirements:
        _method:  GET|POST

backend_check_delete:
    pattern:  /backend/check/delete/{idCheckUrl}
    defaults: { _controller: ApplicationBundle:Check:deleteCheck }
    requirements:
        _method:  GET|DELETE

#################################################################
#Ping Url

backend_pingUrl:
    pattern:  /backend/pingUrl/ping/{idCheckUrl}
    defaults: { _controller: ApplicationBundle:PingUrl:pingUrl }
    requirements:
        _method:  GET

backend_result_pingUrl:
    pattern:  /backend/pingUrl/result
    defaults: { _controller: ApplicationBundle:PingUrl:result }
    requirements:
        _method:  GET

#################################################################
#Ping Url

backend_test_snmp:
    pattern:  /backend/snmp/test
    defaults: { _controller: ApplicationBundle:PingUrl:testSNMP }
    requirements:
        _method:  GET|POST
