monitoring\ApplicationBundle\Entity\checkUrl:
    properties:
        name:
            - NotBlank: ~
        url:
            - NotBlank: ~
#            - Regex:
#                pattern: "/.*\.es$/"
#                message: "La URL debe terminar en .es"
        timeOut:
            - GreaterThan:
                value: 0
                message: "Time Out cannot be less than 1"
            - NotBlank: ~
        pingInterval:
            - GreaterThan:
                value: 0
                message: "Ping Interval cannot be less than 1"
            - NotBlank: ~
        tags:
            - Type:
                type: string
                message: "The value {{ value }} must be a string"

monitoring\ApplicationBundle\Entity\contact:
    properties:
        name:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Regex:
                pattern: "/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/"
                message: "your email adress is incorect"
        phone:
            - NotBlank: ~
            - Regex:
                pattern: "/^(\(?\+?[0-9]*\)?)?[0-9xX_\-\+\.\ \(\)]*$/"
                message: "your phone number is incorrect."
        message:
            - NotBlank: ~