monitoring\ApplicationBundle\Entity\checkUrl:
    properties:
        name:
            - NotBlank: ~
        url:
            - NotBlank: ~
#            - Regex:
#                pattern: "/.*\.es$/"
#                message: "La URL debe terminar en .es"
        timeOut:
            - GreaterThan:
                value: 0
                message: "Time Out cannot be less than 1"
            - NotBlank: ~
        pingInterval:
            - GreaterThan:
                value: 0
                message: "Ping Interval cannot be less than 1"
            - NotBlank: ~
        tags:
            - Type:
                type: string
                message: "The value {{ value }} must be a string"