NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

application:
    resource: "@ApplicationBundle/Resources/config/routing.yml"
    prefix:   /